apiVersion: v1
kind: Secret
metadata:
  name: nexus-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItZGV2LWdmbmV4dXNwLmdmb3VuZHJpZXMuY29tOjUwMDAiOnsidXNlcm5hbWUiOiJvY3B0ZXN0IiwicGFzc3dvcmQiOiJvY3AkdGVzdC4xNyIsImVtYWlsIjoiamdvdGhhbmRAZ2ZvdW5kcmllcy5jb20iLCJhdXRoIjoiYjJOd2RHVnpkRHB2WTNBa2RHVnpkQzR4Tnc9PSJ9fX0=