apiVersion: v1
kind: Secret
metadata:
  name: nexus-pullsecret
  namespace: my-project-1  # Change this if you want to create it in a different namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJkb2NrZXItZGV2LWdmbmV4dXNwLmdmb3VuZHJpZXMuY29tOjUwMDAiOnsi
    dXNlcm5hbWUiOiJvY3B0ZXN0IiwicGFzc3dvcmQiOiJvY3AkdGVzdC4xNyIsImVtYWlsIjoi
    amdvdGhhbmRAZ2ZvdW5kcmllcy5jb20iLCJhdXRoIjoiYjJGb2FXNW5MV1JsYzNRdVkyOXRj
    R2x1WjJWekxXUnZjbXhrWldGMFlTMWpiMjUwWlc1MElHNWxaV1FnYjI1MFpXNTBJRzVqYjIw
    PSJ9fX0=
